### ISSUE TITLE
Hosting on vercel

### ISSUE THREAD

**Issue by sonicx180** [LeoDog896/webpage#1]
Hey @LeoDog896 ! you might want to host this on [Vercel](https://vercel.com) so that it works. good luck!

**Comment by tristan-f-r** [comment]
Hello! I actually just broke the website and forgot to fix it 😝 absolutely thanks for the reminder, but I prefer to use dynamic websites in Vercel. I'll see if I can fix it today 👍

**Comment by sonicx180** [comment]
alrighty thanks!
