### ISSUE TITLE
All braces display as &#123; and &#125;

### ISSUE THREAD

**Issue by jonot-cyber** [LeoDog896/webpage#13]
This can be seen on [making a jigsaw puzzle in godot](https://leodog896.com/article/godot-jigsaw) and [2 ANSI injection vulnerabilities in Deno](https://leodog896.com/article/deno-ansi-injection). "{" is displayed as  "\&#123;", and "}" is displayed as "\&#125;"

using my trusty GNU Emacs, I was able to see that 123 and 125 are the ASCII codes for the braces (`C-x =`), so it probably has to do with that.

if it also helps, I had to put backslashes in my markdown for this issue because otherwise it would replace "\&#123;" with "{"

**Comment by jonot-cyber** [comment]
Should have looked closer at [https://leodog896.com/article/github-catalog](https://leodog896.com/article/github-catalog), but yeah that also has this problem.

**Comment by tristan-f-r** [comment]
Duplicate of #8. I should probably leave one of these open as a tracking issue.
