### ISSUE TITLE
Link && to MDN webpage

### ISSUE THREAD

**Issue by willuhmjs** [LeoDog896/webpage#3]
The Logical AND operator at the top of the webpage is designed to be a link. Perhaps we could link it to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND) on the operator.

**Comment by tristan-f-r** [comment]
Completed in #4.

**Comment by tristan-f-r** [comment]
By the way, I may change this to something like a light/dark mode switcher - haven't added dark mode yet, so thought that would be pretty nice.

**Comment by willuhmjs** [comment]
That would be an interesting choice from an accessibility standpoint considering "&&" doesn't hint to a theme changing button. Perhaps adding a sun/moon icon somewhere on the page (like the navbar) would be a better design choice.
