### ISSUE TITLE
use consistent formatting

### ISSUE THREAD

**Issue by willuhmjs** [LeoDog896/webpage#6]
There are some inconsistency in your formatting. For instance, some proper nouns are capitalized in headers while others are not. Additionally, the descriptions of the first and third items have punctuation, while the second and fourth items to not.

**Comment by tristan-f-r** [comment]
no thanks - i don't have a brand I'm trying to mainly represent on my personal blog. however, the period in the ANSI Deno description is accidental :+1:

**Comment by willuhmjs** [comment]
Even if you don't have a brand, consistency is a key part of good web design.

**Comment by tristan-f-r** [comment]
Consistency is a key part of good web design in pair with branding. However, if you are wondering, my preferred punctuation in this website for the description is either nothing or an exclamation mark (thus the comment above.)

**Comment by willuhmjs** [comment]
Yes, I noticed that and pointed it out by saying that the existence of a period in the first item is unusual. You fixed it, so this should have been closed as resolved. Sorry for any miscommunication.
