### ISSUE TITLE
bug: character entities not rendering correctly

### ISSUE THREAD

**Issue by willuhmjs** [LeoDog896/webpage#8]
Sometimes characters such as the open bracket are rendered as their entity, `&#123;`, instead of their character

**Comment by tristan-f-r** [comment]
This is an upstream issue with [pngwn/MDsveX#304](https://github.com/pngwn/MDsveX/issues/304).

**Comment by tristan-f-r** [comment]
Reopening this as a tracking issue (issue pestering on #13). Plus, unlike #12, I'm quite interested in fixing this myself. I'll see if I can make a patch for mdsvex that resolves this bad toolchain interaction.

**Comment by tristan-f-r** [comment]
Fixed by https://github.com/LeoDog896/webpage/commit/4db08cafa9b8336b87080c78e0dad82686411c8e .. https://github.com/LeoDog896/webpage/commit/575556ac0da168ec9ec26170c4f3167585e9a561
